# Generated by Django 3.1.7 on 2021-03-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variance', models.CharField(max_length=40)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer.polls')),
            ],
        ),
    ]
